name: Build and Release
on: 
  push:
    branches:
      - 'violine-edition'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@749f47bda3e44aa060e82d7b3ef7e40d953bd629
        with:
          arguments: build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Package
          path: build/libs
      - name: Trigger Release
        id: get_version
        run: |
          RELEASE_SCRIPT_RESULT=$(sh ./release_version.sh)
          echo -e $RELEASE_SCRIPT_RESULT
          echo $(echo $RELEASE_SCRIPT_RESULT | grep -Po "CREATE_RELEASE=.*") >> $GITHUB_ENV
      - name: Create release
        uses: softprops/action-gh-release@v2
        if: env.CREATE_RELEASE == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: build/libs
